set_property IOSTANDARD LVCMOS33 [get_ports Vaux4_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux4_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux12_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux12_0_v_p]
set_property PACKAGE_PIN G2 [get_ports Vaux4_0_v_n]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {il_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {il_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saf_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {saf_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {str_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {str_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {str_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {str_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports bplssw_0]
set_property IOSTANDARD LVCMOS33 [get_ports bplssw_pg_0]
set_property IOSTANDARD LVCMOS33 [get_ports ihenv_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports roper_0]
set_property IOSTANDARD LVCMOS33 [get_ports sbf_0]
set_property IOSTANDARD LVCMOS33 [get_ports set_0]
set_property PACKAGE_PIN A16 [get_ports ihenv_0]
set_property PACKAGE_PIN K3 [get_ports roper_0]
set_property PACKAGE_PIN C15 [get_ports {str_0[0]}]
set_property PACKAGE_PIN M3 [get_ports {il_0[2]}]
set_property PACKAGE_PIN L3 [get_ports {il_0[1]}]
set_property PACKAGE_PIN V8 [get_ports sbf_0]
set_property PACKAGE_PIN W7 [get_ports {saf_0[2]}]
set_property PACKAGE_PIN U8 [get_ports {saf_0[1]}]
set_property PACKAGE_PIN H1 [get_ports {str_0[1]}]
set_property PACKAGE_PIN A15 [get_ports {str_0[2]}]
set_property PACKAGE_PIN B15 [get_ports {str_0[3]}]
set_property PACKAGE_PIN J3 [get_ports reset_0]
set_property PACKAGE_PIN J1 [get_ports set_0]
set_property PACKAGE_PIN N2 [get_ports bplssw_pg_0]
set_property PACKAGE_PIN P1 [get_ports bplssw_0]
